# Generated by Django 3.2 on 2021-04-29 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hours_per_week', models.PositiveSmallIntegerField()),
                ('weeks', models.PositiveSmallIntegerField()),
                ('slug', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
                ('topic', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='topic.topic')),
            ],
        ),
    ]
