# Generated by Django 3.2.4 on 2021-06-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0006_auto_20210606_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gp_rate',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gp_rate',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
