# Generated by Django 3.2.4 on 2021-06-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0009_alter_avg_rate_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avg_Rate',
        ),
    ]
