# Generated by Django 3.2 on 2021-04-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
