# Generated by Django 3.2 on 2021-04-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_choice_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
